"" Author: Juan Burgos
"" Purpose: Make VIM Better

"" File
set encoding=utf8

"" Search config
set ignorecase
set smartcase
set hlsearch
set incsearch
set showmatch

"" No annoying dot files created by vim
set nobackup
set nowritebackup
set noswapfile "" Prevents those (dot)swp files
set noundofile "" Prevents those (dot)un~ files

"" Menu config
set wildmenu
set autoread

"" Indent / Tab
set autoindent
set smartindent
set expandtab
set shiftwidth=2
set tabstop=2

"" Scroll
set scrolloff=7

"" Line
set cursorline
set cursorcolumn
set number
set wrap
set magic
set statusline+=%F
set backspace=indent,eol,start
filetype plugin indent on

"" Enable mouse input
set mouse=a

"" Visual config
syntax on
colorscheme evening

"" Make sure makefile editing uses tabs and not spaces
autocmd FileType make setlocal noexpandtab
